# Generated by Django 5.0 on 2024-01-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUserReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('libraryId', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=20)),
                ('reference_by', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='MALE', max_length=6)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('token', models.CharField(default='Error', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='changepassword',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='changepassword',
            name='token',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='SuperUser',
        ),
    ]
