# Generated by Django 4.2.6 on 2023-10-15 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issued_Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_by', models.CharField(default='Null', max_length=30, verbose_name='Issued By')),
                ('email', models.EmailField(default='', max_length=50, verbose_name='Email')),
                ('mobile', models.PositiveIntegerField(verbose_name='Mobile Number')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Issue Date')),
                ('return_date', models.DateField(default='Null', verbose_name='Return Date')),
                ('library_id', models.CharField(default='', max_length=10, verbose_name='Library ID')),
                ('bookName', models.CharField(default='', max_length=255, verbose_name='Book Name')),
                ('department', models.CharField(default='', max_length=50, verbose_name='Department')),
                ('authorName', models.CharField(default='', max_length=50, verbose_name='Author Name')),
                ('ISBN', models.CharField(default='', max_length=255, verbose_name='ISBN Number')),
            ],
        ),
        migrations.CreateModel(
            name='Registered_Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(default='', max_length=255, verbose_name='Book Name')),
                ('department', models.CharField(default='', max_length=50, verbose_name='Department')),
                ('category', models.CharField(default='', max_length=50, verbose_name='Category')),
                ('authorName', models.CharField(default='', max_length=50, verbose_name='Author Name')),
                ('ISBN', models.CharField(default='', max_length=255, verbose_name='ISBN Number')),
                ('bookPrice', models.PositiveIntegerField(default=0, verbose_name='Book Price')),
                ('coverImage', models.ImageField(upload_to='images/', verbose_name='Book Cover Image')),
                ('status', models.CharField(default='', max_length=50, verbose_name='Status')),
                ('last_issued_by', models.CharField(default='null', max_length=30, null=True, verbose_name='Last Issued By')),
                ('last_returned_by', models.CharField(default='null', max_length=30, null=True, verbose_name='Last Returned By')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
            ],
        ),
        migrations.CreateModel(
            name='Returned_Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_by', models.CharField(default='Null', max_length=30, verbose_name='Returned By')),
                ('email', models.EmailField(default='', max_length=50, verbose_name='Email')),
                ('mobile', models.PositiveIntegerField(verbose_name='Mobile Number')),
                ('issue_date', models.DateTimeField(default='Null', verbose_name='Issue Date')),
                ('return_date', models.DateTimeField(auto_now_add=True, verbose_name='Return Date')),
                ('library_id', models.CharField(default='', max_length=10, verbose_name='Library ID')),
                ('bookName', models.CharField(default='', max_length=255, verbose_name='Book Name')),
                ('fine', models.PositiveIntegerField(default=0, verbose_name='FINE (in RS.)')),
                ('department', models.CharField(default='', max_length=50, verbose_name='Department')),
                ('category', models.CharField(default='', max_length=50, verbose_name='Category')),
                ('authorName', models.CharField(default='', max_length=50, verbose_name='Author Name')),
                ('ISBN', models.CharField(default='', max_length=255, verbose_name='ISBN Number')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='USER NAME')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=6)),
                ('department', models.CharField(default='', max_length=20, verbose_name='DEPARTMENT')),
                ('library_id', models.CharField(default='', max_length=10, unique=True, verbose_name='LIBRARY ID')),
                ('mobile', models.CharField(default='', max_length=10, verbose_name='MOBILE NO.')),
                ('joiningYear', models.CharField(default='', max_length=4, verbose_name='ADMISSION YEAR')),
                ('passingYear', models.CharField(default='', max_length=4, verbose_name='PASSING YEAR')),
                ('issuedBooks', models.PositiveIntegerField(default=0, verbose_name='ISSUED BOOKS')),
                ('returnedBooks', models.PositiveIntegerField(default=0, verbose_name='RETURNED BOOKS')),
                ('fine', models.PositiveIntegerField(default=0, verbose_name='FINE (in RS.)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
