# Generated by Django 4.2.6 on 2023-10-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_books',
            name='coverImage',
            field=models.ImageField(upload_to='cover images/', verbose_name='Book Cover Image'),
        ),
    ]
