# Generated by Django 4.2.6 on 2023-10-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_registered_books_coverimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_books',
            name='register_by',
            field=models.CharField(default='', max_length=50, verbose_name='book register by'),
        ),
        migrations.AlterField(
            model_name='registered_books',
            name='ISBN',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='ISBN Number'),
        ),
        migrations.AlterField(
            model_name='registered_books',
            name='status',
            field=models.CharField(default='Available', max_length=50, verbose_name='Status'),
        ),
    ]
