# Generated by Django 5.0 on 2024-01-19 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_registered_books_bookname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_books',
            name='billNo_Date',
            field=models.TextField(default='Not Available', verbose_name='Bill No and Date'),
        ),
        migrations.AddField(
            model_name='registered_books',
            name='bookPages',
            field=models.IntegerField(default=0, verbose_name='Book Pages'),
        ),
        migrations.AddField(
            model_name='registered_books',
            name='bookSource',
            field=models.TextField(default='Not Available', verbose_name='Book Source'),
        ),
        migrations.AddField(
            model_name='registered_books',
            name='coverImage',
            field=models.ImageField(default='', upload_to='cover images/', verbose_name='Book Cover Image'),
        ),
        migrations.AddField(
            model_name='registered_books',
            name='last_issued_by',
            field=models.CharField(default='null', max_length=30, null=True, verbose_name='Last Issued By'),
        ),
        migrations.AddField(
            model_name='registered_books',
            name='last_returned_by',
            field=models.CharField(default='null', max_length=30, null=True, verbose_name='Last Returned By'),
        ),
        migrations.AddField(
            model_name='registered_books',
            name='printYear',
            field=models.IntegerField(default=0, verbose_name='Printed Year'),
        ),
        migrations.AddField(
            model_name='registered_books',
            name='purchaseDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Purchase Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registered_books',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registered At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registered_books',
            name='status',
            field=models.CharField(default='Available', max_length=30, verbose_name='Status'),
        ),
    ]
