# Generated by Django 5.0 on 2024-01-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_registered_books_billno_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_books',
            name='ISBN',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='ISBN Number'),
        ),
        migrations.AddField(
            model_name='registered_books',
            name='authorName',
            field=models.CharField(default='', max_length=50, verbose_name='Author Name'),
        ),
        migrations.AddField(
            model_name='registered_books',
            name='bookPrice',
            field=models.PositiveIntegerField(default=0, verbose_name='Book Price'),
        ),
        migrations.AddField(
            model_name='registered_books',
            name='category',
            field=models.CharField(default='Null', max_length=50, verbose_name='Category'),
        ),
    ]
