# Generated by Django 5.0 on 2024-01-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_registered_books_isbn_registered_books_authorname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_books',
            name='place_and_publisher',
            field=models.TextField(default='Null', verbose_name='Place And Publisher'),
        ),
    ]
