# Generated by Django 4.2.6 on 2023-10-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='issued_books',
            name='status',
            field=models.CharField(default='Issued', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='issued_books',
            name='issue_date',
            field=models.CharField(default='Null', max_length=15, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='issued_books',
            name='return_date',
            field=models.CharField(default='Null', max_length=15, verbose_name='Return Date'),
        ),
        migrations.AlterField(
            model_name='registered_books',
            name='status',
            field=models.CharField(default='Available', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='returned_books',
            name='issue_date',
            field=models.CharField(default='Null', max_length=15, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='returned_books',
            name='return_date',
            field=models.CharField(default='Null', max_length=15, verbose_name='Return Date'),
        ),
    ]
