# Generated by Django 4.2.6 on 2023-10-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_issued_books_status_alter_issued_books_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issued_books',
            name='category',
            field=models.CharField(default='', max_length=50, verbose_name='Category'),
        ),
    ]
