# Generated by Django 5.0 on 2024-01-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_registered_books_place_and_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_books',
            name='bookContact',
            field=models.TextField(default='Null', verbose_name='Call No.'),
        ),
        migrations.AddField(
            model_name='registered_books',
            name='edition',
            field=models.CharField(default='', max_length=10, verbose_name='Edition'),
        ),
        migrations.AddField(
            model_name='registered_books',
            name='volume',
            field=models.CharField(default='', max_length=10, verbose_name='Volume'),
        ),
        migrations.AddField(
            model_name='registered_books',
            name='withDrawDate',
            field=models.TextField(default='', verbose_name='WithDraw Date & Remarks'),
        ),
    ]
