# Generated by Django 5.0 on 2024-01-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_alter_registered_books_bookpages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_books',
            name='bookPages',
            field=models.CharField(default='Null', max_length=30, null=True, verbose_name='Book Pages'),
        ),
    ]
