# Generated by Django 5.0 on 2023-12-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_alter_registered_books_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='departmentName',
        ),
    ]
