# Generated by Django 5.0 on 2024-01-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_alter_registered_books_bookcontact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_books',
            name='withDrawDate',
            field=models.TextField(default='Null', null=True, verbose_name='WithDraw Date & Remarks'),
        ),
    ]
