# Generated by Django 5.0 on 2024-01-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_alter_registered_books_withdrawdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_books',
            name='department',
            field=models.CharField(default='Null', max_length=50, null=True, verbose_name='Department'),
        ),
    ]
