# Generated by Django 5.0 on 2024-01-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_alter_registered_books_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='semester',
            field=models.CharField(default='', max_length=10, verbose_name='Semester'),
        ),
    ]
