# Generated by Django 5.0 on 2024-01-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_profile_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='issued_books',
            name='semester',
            field=models.CharField(default='', max_length=10, verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='returned_books',
            name='semester',
            field=models.CharField(default='', max_length=10, verbose_name='Semester'),
        ),
    ]
