# Generated by Django 5.0 on 2024-01-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0017_alter_profile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='returned_books',
            name='isPaid',
        ),
    ]
