# Generated by Django 5.0 on 2024-02-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0018_remove_profile_fine_remove_returned_books_ispaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returned_books',
            name='department',
        ),
        migrations.AddField(
            model_name='returned_books',
            name='std_department',
            field=models.CharField(default='', max_length=50, verbose_name=' Student Department'),
        ),
    ]
